In [1]:
# Import relevant packages
#Import Modules
import os
import numpy as np
import pandas as pd
import requests
import datetime as dt
import random
# BDay is business day
from pandas.tseries.offsets import BDay
import math
import time
import calendar
import re
from sqlalchemy import create_engine
import pymysql
import warnings
warnings.filterwarnings('ignore')
from sqlalchemy.orm import Session
from Config import pwd, user, host, port, dbname

In [2]:
pymysql.install_as_MySQLdb() 
string = f"mysql://{user}:{pwd}@{host}/{dbname}"
engine = create_engine(string)
# Establish a connection to the local DB
conn = engine.connect()
# Import and establish Base for which classes will be constructed
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float

In [3]:
##pull in stock list from sql table
stock = pd.read_sql('select distinct(symbol) from sandp_stocks;', con=conn)
stock_list = stock['symbol'].tolist()
stock_list

['MMM',
 'ABT',
 'ABBV',
 'ABMD',
 'ACN',
 'ATVI',
 'ADBE',
 'AMD',
 'AAP',
 'AES',
 'AMG',
 'AFL',
 'A',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALXN',
 'ALGN',
 'ALLE',
 'AGN',
 'ADS',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'ABC',
 'AME',
 'AMGN',
 'APH',
 'APC',
 'ADI',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'AIV',
 'AAPL',
 'AMAT',
 'APTV',
 'ADM',
 'ARNC',
 'ANET',
 'AJG',
 'AIZ',
 'ATO',
 'T',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'BHGE',
 'BLL',
 'BAC',
 'BK',
 'BAX',
 'BBT',
 'BDX',
 'BRK-B',
 'BBY',
 'BIIB',
 'BLK',
 'HRB',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BHF',
 'BMY',
 'AVGO',
 'BR',
 'BF-B',
 'CHRW',
 'COG',
 'CDNS',
 'CPB',
 'COF',
 'CPRI',
 'CAH',
 'KMX',
 'CCL',
 'CAT',
 'CBOE',
 'CBRE',
 'CBS',
 'CE',
 'CELG',
 'CNC',
 'CNP',
 'CTL',
 'CERN',
 'CF',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'XEC',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CTXS',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'CXO',
 'COP',
 'ED',
 'STZ',
 'COO',
 'CPRT',
 'GLW',
 'COST',
 'COTY',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHI',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'FANG',
 'DLR',
 'DFS',
 'DISCA',
 'DISCK',
 'DISH',
 'DG',
 'DLTR',
 'D',
 'DOV',
 'DWDP',
 'DTE',
 'DRE',
 'DUK',
 'DXC',
 'ETFC',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'EMR',
 'ETR',
 'EOG',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'EVRG',
 'ES',
 'RE',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FB',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FE',
 'FRC',
 'FISV',
 'FLT',
 'FLIR',
 'FLS',
 'FLR',
 'FMC',
 'FL',
 'F',
 'FTNT',
 'FTV',
 'FBHS',
 'BEN',
 'FCX',
 'GPS',
 'GRMN',
 'IT',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GS',
 'GT',
 'GWW',
 'HAL',
 'HBI',
 'HOG',
 'HRS',
 'HIG',
 'HAS',
 'HCA',
 'HCP',
 'HP',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HFC',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HPQ',
 'HUM',
 'HBAN',
 'HII',
 'IDXX',
 'INFO',
 'ITW',
 'ILMN',
 'IR',
 'INTC',
 'ICE',
 'IBM',
 'INCY',
 'IP',
 'IPG',
 'IFF',
 'INTU',
 'ISRG',
 'IVZ',
 'IPGP',
 'IQV',
 'IRM',
 'JKHY',
 'JEC',
 'JBHT',
 'JEF',
 'SJM',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'KSU',
 'K',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KSS',
 'KHC',
 'KR',
 'LB',
 'LLL',
 'LH',
 'LRCX',
 'LW',
 'LEG',
 'LEN',
 'LLY',
 'LNC',
 'LIN',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LYB',
 'MTB',
 'MAC',
 'M',
 'MRO',
 'MPC',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MAT',
 'MKC',
 'MXIM',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MHK',
 'TAP',
 'MDLZ',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'MYL',
 'NDAQ',
 'NOV',
 'NKTR',
 'NTAP',
 'NFLX',
 'NWL',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NLSN',
 'NKE',
 'NI',
 'NBL',
 'JWN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'ORLY',
 'OXY',
 'OMC',
 'OKE',
 'ORCL',
 'PCAR',
 'PKG',
 'PH',
 'PAYX',
 'PYPL',
 'PNR',
 'PBCT',
 'PEP',
 'PKI',
 'PRGO',
 'PFE',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'RL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PSA',
 'PHM',
 'PVH',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RJF',
 'RTN',
 'O',
 'RHT',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SEE',
 'SRE',
 'SHW',
 'SPG',
 'SWKS',
 'SLG',
 'SNA',
 'SO',
 'LUV',
 'SPGI',
 'SWK',
 'SBUX',
 'STT',
 'SYK',
 'STI',
 'SIVB',
 'SYMC',
 'SYF',
 'SNPS',
 'SYY',
 'TROW',
 'TTWO',
 'TPR',
 'TGT',
 'TEL',
 'FTI',
 'TFX',
 'TXN',
 'TXT',
 'TMO',
 'TIF',
 'TWTR',
 'TJX',
 'TMK',
 'TSS',
 'TSCO',
 'TDG',
 'TRV',
 'TRIP',
 'FOXA',
 'FOX',
 'TSN',
 'UDR',
 'ULTA',
 'USB',
 'UAA',
 'UA',
 'UNP',
 'UAL',
 'UNH',
 'UPS',
 'URI',
 'UTX',
 'UHS',
 'UNM',
 'VFC',
 'VLO',
 'VAR',
 'VTR',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VIAB',
 'V',
 'VNO',
 'VMC',
 'WMT',
 'WBA',
 'DIS',
 'WM',
 'WAT',
 'WEC',
 'WCG',
 'WFC',
 'WELL',
 'WDC',
 'WU',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WLTW',
 'WYNN',
 'XEL',
 'XRX',
 'XLNX',
 'XYL',
 'YUM',
 'ZBH',
 'ZION',
 'ZTS']

In [4]:
# parse EBITA value from yahoo finance table
# to_frame = []
# for symbol in stock_list:
#     try:
#         df = pd.read_html(f"https://finance.yahoo.com/quote/{symbol}/key-statistics?p={symbol}")
#         Enterprise_Value_EBITDA = df[0]
#         Enterprise_Value_EBITDA = Enterprise_Value_EBITDA[Enterprise_Value_EBITDA[0].str.contains("Enterprise Value/EBITDA") == True][1].values[0]
#         print(Enterprise_Value_EBITDA)
#         to_store = {"symbol":symbol,
#                 "model": "EBITDA_Multiple",
#                 "value": Enterprise_Value_EBITDA}
#         to_frame.append(to_store)
#     except:
#         print(f"Passed {symbol}")

In [5]:
# frame_to_push = pd.DataFrame(to_frame)
# frame_to_push

In [6]:
# # setup pymysql and connect to local MySQL workbench
# pwd="N1i2s3h4i5t6"
# pymysql.install_as_MySQLdb() 
# string = f"mysql://root:{pwd}@localhost:3306/stock_data"
# engine = create_engine(string)
# # Establish a connection to the local DB
# conn = engine.connect()
# # Import and establish Base for which classes will be constructed
# from sqlalchemy.ext.declarative import declarative_base
# Base = declarative_base()
# # Import modules to declare columns and column data types
# from sqlalchemy import Column, Integer, String, Float

In [7]:
#   class sector_yony_dividend (Base):
#     __tablename__ = 'EBITA_Multiple_2'
#     symbol = Column(String(100),primary_key=True)
#     model = Column("model",String(100))
#     value = Column("value",Float)

In [8]:
# # Create both the company_diversity_m_f and company_diversity_race tables within the database
# Base.metadata.create_all(conn)
# # confirming that tables got created in the DB
# engine.table_names()
# # Create a session that binds to the engine to enable insert of data
# session = Session(bind=engine)

In [9]:
# frame_to_push.to_sql(name="EBITA_Multiple_1", con=engine, if_exists='append',index=False)

In [10]:
# EBITA_Multiple_pulled = pd.read_sql("select * from EBITA_Multiple_1", con=engine)

In [11]:
# EBITA_Multiple_table = EBITA_Multiple_pulled

In [12]:
# nans = EBITA_Multiple_table.notna().groupby("value")

In [13]:
# nans.count()

In [14]:
# stock = pd.read_sql('select * from sandp_stocks;', con=conn)

In [15]:
# merged = stock.merge(EBITA_Multiple_table,on="symbol")

In [16]:
# merged.to_excel("merged_table.xlsx")

In [17]:
df = pd.read_excel("merged_table.xlsx")

In [18]:
df

,index,security,symbol,sec_filing,gics_sector,gics_sub_industry,hq_location,date_added,cik,year_founded,model,value
0,1,3M Company,MMM,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902,EBITDA_Multiple,15.48
1,2,Abbott Laboratories,ABT,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888,EBITDA_Multiple,21.20
2,3,AbbVie Inc.,ABBV,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),EBITDA_Multiple,10.96
3,4,ABIOMED Inc,ABMD,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981,EBITDA_Multiple,64.16
4,5,Accenture plc,ACN,reports,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,EBITDA_Multiple,15.43
5,6,Activision Blizzard,ATVI,reports,Communication Services,Interactive Home Entertainment,"Santa Monica, California",2015-08-31,718877,2008,EBITDA_Multiple,13.60
6,7,Adobe Systems Inc,ADBE,reports,Information Technology,Application Software,"San Jose, California",1997-05-05,796343,1982,EBITDA_Multiple,39.31
7,8,Advanced Micro Devices Inc,AMD,reports,Information Technology,Semiconductors,"Sunnyvale, California",2017-03-20,2488,1969,EBITDA_Multiple,39.95
8,9,Advance Auto Parts,AAP,reports,Consumer Discretionary,Automotive Retail,"Roanoke, Virginia",2015-07-09,1158449,1932,EBITDA_Multiple,12.52
9,10,AES Corp,AES,reports,Utilities,Independent Power Producers & Energy Traders,"Arlington, Virginia",1998-10-02,874761,1981,EBITDA_Multiple,9.55
10,11,Affiliated Managers Group Inc,AMG,reports,Financials,Asset Management & Custody Banks,"Beverly, Massachusetts",2014-07-01,1004434,1993,EBITDA_Multiple,8.64
11,12,AFLAC Inc,AFL,reports,Financials,Life & Health Insurance,"Columbus, Georgia",1999-05-28,4977,1955,EBITDA_Multiple,9.27
12,13,Agilent Technologies Inc,A,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999,EBITDA_Multiple,20.67
13,14,Air Products & Chemicals Inc,APD,reports,Materials,Industrial Gases,"Allentown, Pennsylvania",1985-04-30,2969,1940,EBITDA_Multiple,14.09
14,15,Akamai Technologies Inc,AKAM,reports,Information Technology,Internet Services & Infrastructure,"Cambridge, Massachusetts",2007-07-12,1086222,1998,EBITDA_Multiple,15.68
15,16,Alaska Air Group Inc,ALK,reports,Industrials,Airlines,"Seattle, Washington",2016-05-13,766421,1985,EBITDA_Multiple,6.32
16,17,Albemarle Corp,ALB,reports,Materials,Specialty Chemicals,"Baton Rouge, Louisiana",2016-07-01,915913,1994,EBITDA_Multiple,10.55
17,18,Alexandria Real Estate Equities,ARE,reports,Real Estate,Office REITs,"Pasadena, California",2017-03-20,1035443,1994,EBITDA_Multiple,26.10
18,19,Alexion Pharmaceuticals,ALXN,reports,Health Care,Biotechnology,"Cheshire, Connecticut",2012-05-25,899866,1992,EBITDA_Multiple,15.37
19,20,Align Technology,ALGN,reports,Health Care,Health Care Supplies,"San Jose, California",2017-06-19,1097149,1997,EBITDA_Multiple,39.51
20,21,Allegion,ALLE,reports,Industrials,Building Products,"Dublin, Ireland",2013-12-02,1579241,1908,EBITDA_Multiple,15.43
21,22,"Allergan, Plc",AGN,reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983,EBITDA_Multiple,10.04
22,23,Alliance Data Systems,ADS,reports,Information Technology,Data Processing & Outsourced Services,"Plano, Texas",2013-12-23,1101215,1996,EBITDA_Multiple,16.11
23,24,Alliant Energy Corp,LNT,reports,Utilities,Electric Utilities,"Madison, Wisconsin",2016-07-01,352541,1917,EBITDA_Multiple,14.68
24,25,Allstate Corp,ALL,reports,Financials,Property & Casualty Insurance,"Northfield Township, Illinois",1995-07-13,899051,1931,EBITDA_Multiple,9.86
25,26,Alphabet Inc Class A,GOOGL,reports,FAANG,Communication Services__Interactive Media & Se...,"Mountain View, California",2014-04-03,1652044,1998,EBITDA_Multiple,18.17
26,27,Alphabet Inc Class C,GOOG,reports,FAANG,Communication Services__Interactive Media & Se...,"Mountain View, California",2006-04-03,1652044,1998,EBITDA_Multiple,18.13
27,28,Altria Group Inc,MO,reports,Consumer Staples,Tobacco,"Richmond, Virginia",NaN,764180,1985,EBITDA_Multiple,12.84
28,29,Amazon.com Inc.,AMZN,reports,FAANG,Consumer Discretionary__Internet & Direct Mark...,"Seattle, Washington",2005-11-18,1018724,1994,EBITDA_Multiple,31.51
29,30,Ameren Corp,AEE,reports,Utilities,Multi-Utilities,"St. Louis, Missouri",1991-09-19,1002910,1902,EBITDA_Multiple,11.47
...,...,...,...,...,...,...,...,...,...,...,...,...
475,476,Vertex Pharmaceuticals Inc,VRTX,reports,Health Care,Biotechnology,"Cambridge, Massachusetts",2013-09-23,875320,NaN,EBITDA_Multiple,59.52
476,477,Viacom Inc.,VIAB,reports,Communication Services,Movies & Entertainment,"New York, New York",NaN,1339947,NaN,EBITDA_Multiple,6.23
477,478,Visa Inc.,V,reports,Information Technology,Internet Software & Services,"San Francisco, California",2009-12-21,1403161,NaN,EBITDA_Multiple,24.30
478,479,Vornado Realty Trust,VNO,reports,Real Estate,Office REITs,"New York, New York",NaN,899689,NaN,EBITDA_Multiple,24.98
479,480,Vulcan Materials,VMC,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN,EBITDA_Multiple,15.87
480,481,Walmart,WMT,reports,Consumer Staples,Hypermarkets & Super Centers,"Bentonville, Arkansas",1982-08-31,104169,NaN,EBITDA_Multiple,10.48
481,482,Walgreens Boots Alliance,WBA,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,NaN,EBITDA_Multiple,9.47
482,483,The Walt Disney Company,DIS,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN,EBITDA_Multiple,10.47
483,484,Waste Management Inc.,WM,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968,EBITDA_Multiple,13.42
484,485,Waters Corporation,WAT,reports,Health Care,Health Care Distributors,"Milford, Massachusetts",NaN,1000697,1958,EBITDA_Multiple,20.01
485,486,Wec Energy Group Inc,WEC,reports,Utilities,Electric Utilities,"Milwaukee, Wisconsin",2008-10-31,783325,NaN,EBITDA_Multiple,15.72
486,487,WellCare,WCG,reports,Health Care,Managed Health Care,"Tampa, Florida",1985,1279363,NaN,EBITDA_Multiple,10.57
487,488,Wells Fargo,WFC,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971,NaN,EBITDA_Multiple,NaN
488,489,Welltower Inc.,WELL,reports,Real Estate,Health Care REITs,"Toledo, Ohio",2009-01-30,766704,NaN,EBITDA_Multiple,21.50
489,490,Western Digital,WDC,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Irvine, California",2009-07-01,106040,NaN,EBITDA_Multiple,4.36
490,491,Western Union Co,WU,reports,Information Technology,Internet Software & Services,"Englewood, Colorado",NaN,1365135,1851,EBITDA_Multiple,7.57
491,492,WestRock,WRK,reports,Materials,Paper Packaging,"Richmond, Virginia",NaN,1636023,NaN,EBITDA_Multiple,6.97
492,493,Weyerhaeuser,WY,reports,Real Estate,Specialized REITs,"Federal Way, Washington",NaN,106535,NaN,EBITDA_Multiple,13.73
493,494,Whirlpool Corp.,WHR,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911,EBITDA_Multiple,7.16
494,495,Williams Cos.,WMB,reports,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",1975-03-31,107263,NaN,EBITDA_Multiple,15.89
495,496,Willis Towers Watson,WLTW,reports,Financials,Insurance Brokers,"London, United Kingdom",2016-01-05,1140536,NaN,EBITDA_Multiple,13.86
496,497,Wynn Resorts Ltd,WYNN,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN,EBITDA_Multiple,10.79
497,498,Xcel Energy Inc,XEL,reports,Utilities,Multi-Utilities,"Minneapolis, Minnesota",NaN,72903,1909,EBITDA_Multiple,12.77
498,499,Xerox,XRX,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Norwalk, Connecticut",NaN,108772,1906,EBITDA_Multiple,8.31
499,500,Xilinx,XLNX,reports,Information Technology,Semiconductors,"San Jose, California",1999-11-08,743988,NaN,EBITDA_Multiple,27.94
500,501,Xylem Inc.,XYL,reports,Industrials,Industrial Machinery,"White Plains, New York",2011-11-01,1524472,NaN,EBITDA_Multiple,16.65
501,502,Yum! Brands Inc,YUM,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,NaN,EBITDA_Multiple,21.11
502,503,Zimmer Biomet Holdings,ZBH,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN,EBITDA_Multiple,14.41
503,504,Zions Bancorp,ZION,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,NaN,EBITDA_Multiple,NaN
504,505,Zoetis,ZTS,reports,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,NaN,EBITDA_Multiple,23.73

In [19]:
sub_mean = df.groupby("gics_sub_industry").mean()
sub_mean.head()

                                    index            cik      value
gics_sub_industry
Advertising                    309.500000   40816.500000   8.740000
Aerospace & Defense            292.916667  626169.166667  12.315833
Agricultural & Farm Machinery  147.000000  315189.000000  15.350000
Agricultural Products           53.000000    7084.000000  10.580000
Air Freight & Logistics        233.000000  982357.500000  11.947500

In [20]:
average_sub_industry = sub_mean["value"]

In [21]:
average_sub_industry = average_sub_industry.to_frame()

In [22]:
average_sub_industry.head()

                                   value
gics_sub_industry
Advertising                     8.740000
Aerospace & Defense            12.315833
Agricultural & Farm Machinery  15.350000
Agricultural Products          10.580000
Air Freight & Logistics        11.947500

In [23]:
df2 = df.merge(average_sub_industry, on="gics_sub_industry")

In [24]:
df2.rename(columns={"value_x": "ebita_multiple","value_y":"sub_industry_average"}, inplace=True)

In [25]:
# df2["percent_change"] = ((df2["ebita_multiple"]-df2["sub_industry_average"])/df2["sub_industry_average"])*100
df2["percent_change"] = ((df2["sub_industry_average"]-df2["ebita_multiple"])/df2["ebita_multiple"])*100

In [26]:
df2.to_excel("final.xlsx")

In [27]:
df2

,index,security,symbol,sec_filing,gics_sector,gics_sub_industry,hq_location,date_added,cik,year_founded,model,ebita_multiple,sub_industry_average,percent_change
0,1,3M Company,MMM,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902,EBITDA_Multiple,15.48,15.850000,2.390181
1,216,General Electric,GE,reports,Industrials,Industrial Conglomerates,"Boston, Massachusetts",NaN,40545,1892,EBITDA_Multiple,12.68,15.850000,25.000000
2,242,Honeywell Int'l Inc.,HON,reports,Industrials,Industrial Conglomerates,"Morristown, New Jersey",1964-03-31,773840,1906,EBITDA_Multiple,13.29,15.850000,19.262603
3,407,Roper Technologies,ROP,reports,Industrials,Industrial Conglomerates,"Sarasota, Florida",2009-12-23,882835,NaN,EBITDA_Multiple,21.95,15.850000,-27.790433
4,2,Abbott Laboratories,ABT,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888,EBITDA_Multiple,21.20,24.537368,15.742304
5,4,ABIOMED Inc,ABMD,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981,EBITDA_Multiple,64.16,24.537368,-61.755972
6,13,Agilent Technologies Inc,A,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999,EBITDA_Multiple,20.67,24.537368,18.710055
7,69,Baxter International Inc.,BAX,reports,Health Care,Health Care Equipment,"Deerfield, Illinois",1972-09-30,10456,1931,EBITDA_Multiple,16.04,24.537368,52.976112
8,71,Becton Dickinson,BDX,reports,Health Care,Health Care Equipment,"Franklin Lakes, New Jersey",1972-09-30,10795,1897,EBITDA_Multiple,16.67,24.537368,47.194772
9,81,Boston Scientific,BSX,reports,Health Care,Health Care Equipment,"Marlborough, Massachusetts[6]",1995-02-24,885725,NaN,EBITDA_Multiple,22.40,24.537368,9.541823
10,144,Danaher Corp.,DHR,reports,Health Care,Health Care Equipment,"Washington, D.C.",NaN,313616,1969,EBITDA_Multiple,20.75,24.537368,18.252378
11,172,Edwards Lifesciences,EW,reports,Health Care,Health Care Equipment,"Irvine, California",2011-04-01,1099800,NaN,EBITDA_Multiple,33.83,24.537368,-27.468612
12,240,Hologic,HOLX,reports,Health Care,Health Care Equipment,"Marlborough, Massachusetts",2016-03-30,859737,NaN,EBITDA_Multiple,15.05,24.537368,63.038993
13,249,IDEXX Laboratories,IDXX,reports,Health Care,Health Care Equipment,"Westbrook, Maine",2017-01-05,874716,NaN,EBITDA_Multiple,34.22,24.537368,-28.295241
14,262,Intuitive Surgical Inc.,ISRG,reports,Health Care,Health Care Equipment,"Sunnyvale, California",2008-06-02,1035267,NaN,EBITDA_Multiple,44.85,24.537368,-45.290148
15,317,Medtronic plc,MDT,reports,Health Care,Health Care Equipment,"Dublin, Ireland",1986-10-31,64670,NaN,EBITDA_Multiple,14.18,24.537368,73.042090
16,371,PerkinElmer,PKI,reports,Health Care,Health Care Equipment,"Waltham, Massachusetts",1985-05-31,31791,NaN,EBITDA_Multiple,21.65,24.537368,13.336575
17,403,ResMed,RMD,reports,Health Care,Health Care Equipment,"San Diego, California",2017-07-26,943819,NaN,EBITDA_Multiple,20.91,24.537368,17.347530
18,427,Stryker Corp.,SYK,reports,Health Care,Health Care Equipment,"Kalamazoo, Michigan",2000-12-12,310764,NaN,EBITDA_Multiple,20.60,24.537368,19.113439
19,440,Teleflex Inc,TFX,reports,Health Care,Health Care Equipment,"Wayne, Pennsylvania",2019-01-18,96943,1943,EBITDA_Multiple,23.52,24.537368,4.325546
20,443,Thermo Fisher Scientific,TMO,reports,Health Care,Health Care Equipment,"Waltham, Massachusetts",NaN,97745,2006,EBITDA_Multiple,19.86,24.537368,23.551704
21,471,Varian Medical Systems,VAR,reports,Health Care,Health Care Equipment,"Palo Alto, California",2007-02-12,203527,NaN,EBITDA_Multiple,21.24,24.537368,15.524333
22,503,Zimmer Biomet Holdings,ZBH,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN,EBITDA_Multiple,14.41,24.537368,70.280142
23,3,AbbVie Inc.,ABBV,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),EBITDA_Multiple,10.96,12.915000,17.837591
24,22,"Allergan, Plc",AGN,reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983,EBITDA_Multiple,10.04,12.915000,28.635458
25,272,Johnson & Johnson,JNJ,reports,Health Care,Pharmaceuticals,"New Brunswick, New Jersey",1973-06-30,200406,1886,EBITDA_Multiple,13.24,12.915000,-2.454683
26,294,Lilly (Eli) & Co.,LLY,reports,Health Care,Pharmaceuticals,"Indianapolis, Indiana",1970-12-31,59478,1876,EBITDA_Multiple,17.61,12.915000,-26.660988
27,318,Merck & Co.,MRK,reports,Health Care,Pharmaceuticals,"Whitehouse Station, New Jersey",NaN,310158,1891,EBITDA_Multiple,17.48,12.915000,-26.115561
28,335,Mylan N.V.,MYL,reports,Health Care,Pharmaceuticals,"Amsterdam, Netherlands",2004-04-23,69499,NaN,EBITDA_Multiple,7.83,12.915000,64.942529
29,338,Nektar Therapeutics,NKTR,reports,Health Care,Pharmaceuticals,"San Francisco, California",2018-03-19,906709,NaN,EBITDA_Multiple,6.46,12.915000,99.922601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,326,Mohawk Industries,MHK,reports,Consumer Discretionary,Home Furnishings,"Amsterdam, New York",2013-12-23,851968,NaN,EBITDA_Multiple,7.11,8.995000,26.511955
476,297,LKQ Corporation,LKQ,reports,Consumer Discretionary,Distributors,"Chicago, Illinois",2016-05-23,1065696,NaN,EBITDA_Multiple,10.47,10.470000,0.000000
477,304,Macy's Inc.,M,reports,Consumer Discretionary,Department Stores,"Cincinnati, Ohio",NaN,794367,1929,EBITDA_Multiple,4.33,4.820000,11.316397
478,350,Nordstrom,JWN,reports,Consumer Discretionary,Department Stores,"Seattle, Washington",1986-08-31,72333,NaN,EBITDA_Multiple,5.31,4.820000,-9.227872
479,309,Martin Marietta Materials,MLM,reports,Materials,Construction Materials,"Raleigh, North Carolina",2014-07-02,916076,NaN,EBITDA_Multiple,14.36,15.115000,5.257660
480,480,Vulcan Materials,VMC,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN,EBITDA_Multiple,15.87,15.115000,-4.757404
481,321,MGM Resorts International,MGM,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2017-07-26,789570,NaN,EBITDA_Multiple,12.63,11.710000,-7.284244
482,497,Wynn Resorts Ltd,WYNN,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN,EBITDA_Multiple,10.79,11.710000,8.526413
483,327,Molson Coors Brewing Company,TAP,reports,Consumer Staples,Brewers,"Denver, Colorado",1976-06-30,24545,NaN,EBITDA_Multiple,9.83,9.830000,0.000000
484,340,Netflix Inc.,NFLX,reports,FAANG,Communication Services__Movies & Entertainment,"Los Gatos, California",2010-12-20,1065280,1997,EBITDA_Multiple,97.24,97.240000,0.000000
485,341,Newell Brands,NWL,reports,Consumer Discretionary,Housewares & Specialties,"Sandy Springs, Georgia",1989-04-30,814453,NaN,EBITDA_Multiple,14.05,14.050000,0.000000
486,342,Newmont Mining Corporation,NEM,reports,Materials,Gold,"Denver, Colorado",1969-06-30,1164727,1921,EBITDA_Multiple,7.38,7.380000,0.000000
487,343,News Corp. Class A,NWSA,reports,Communication Services,Publishing,"New York, New York",2013-08-01,1564708,NaN,EBITDA_Multiple,8.11,8.110000,0.000000
488,344,News Corp. Class B,NWS,reports,Communication Services,Publishing,"New York, New York",2015-09-18,1564708,NaN,EBITDA_Multiple,8.11,8.110000,0.000000
489,356,Nucor Corp.,NUE,reports,Materials,Steel,"Charlotte, North Carolina",1985-04-30,73309,NaN,EBITDA_Multiple,5.03,5.030000,0.000000
490,369,People's United Financial,PBCT,reports,Financials,Thrifts & Mortgage Finance,"Bridgeport, Connecticut",2008-11-13,1378946,NaN,EBITDA_Multiple,NaN,NaN,NaN
491,402,Republic Services Inc,RSG,reports,Industrials,Environmental & Facilities Services,"Phoenix, Arizona",2008-12-05,1060391,NaN,EBITDA_Multiple,12.05,20.166667,67.358230
492,406,Rollins Inc.,ROL,reports,Industrials,Environmental & Facilities Services,"Atlanta, Georgia",2018-10-01,84839,NaN,EBITDA_Multiple,35.03,20.166667,-42.430298
493,484,Waste Management Inc.,WM,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968,EBITDA_Multiple,13.42,20.166667,50.273224
494,404,Robert Half International,RHI,reports,Industrials,Human Resource & Employment Services,"Menlo Park, California",2000-12-05,315213,NaN,EBITDA_Multiple,11.00,11.000000,0.000000
495,433,Sysco Corp.,SYY,reports,Consumer Staples,Food Distributors,"Houston, Texas",1986-12-31,96021,NaN,EBITDA_Multiple,12.59,12.590000,0.000000
496,445,"Twitter, Inc.",TWTR,reports,Communication Services,Interactive Media & Services,"San Francisco, California",2018-06-07,1418091,NaN,EBITDA_Multiple,28.21,27.655000,-1.967387
497,452,TripAdvisor,TRIP,reports,Communication Services,Interactive Media & Services,"Newton, Massachusetts",2011-12-21,1526520,NaN,EBITDA_Multiple,27.10,27.655000,2.047970
498,453,Twenty-First Century Fox Class A,FOXA,reports,Communication Services,Movies & Entertainment,"New York, New York",2013-07-01,1308161,NaN,EBITDA_Multiple,NaN,8.350000,NaN
499,454,Twenty-First Century Fox Class B,FOX,reports,Communication Services,Movies & Entertainment,"New York, New York",2015-09-18,1308161,NaN,EBITDA_Multiple,NaN,8.350000,NaN
500,477,Viacom Inc.,VIAB,reports,Communication Services,Movies & Entertainment,"New York, New York",NaN,1339947,NaN,EBITDA_Multiple,6.23,8.350000,34.028892
501,483,The Walt Disney Company,DIS,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN,EBITDA_Multiple,10.47,8.350000,-20.248329
502,465,"United Rentals, Inc.",URI,reports,Industrials,Trading Companies & Distributors,"Stamford, Connecticut",2014-09-20,1067701,NaN,EBITDA_Multiple,8.59,8.590000,0.000000
503,482,Walgreens Boots Alliance,WBA,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,NaN,EBITDA_Multiple,9.47,9.470000,0.000000
504,494,Whirlpool Corp.,WHR,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911,EBITDA_Multiple,7.16,7.160000,0.000000

In [28]:
# to_frame = []
# for symbol in stock_list:
#     try:
#         df = pd.read_html(f"https://finance.yahoo.com/quote/{symbol}?p={symbol}&.tsrc=fin-srch")
#         value = df[0].iloc[0].values[1]
#         to_store = {"symbol":symbol,
#                 "current_price": value}
#         to_frame.append(to_store)
#         print(to_store)
#     except:
#         print(f"Passed {symbol}")

In [29]:
# frame_to_push = pd.DataFrame(to_frame)
# print(frame_to_push)

In [30]:
# # setup pymysql and connect to local MySQL workbench
# pwd="N1i2s3h4i5t6"
# pymysql.install_as_MySQLdb() 
# string = f"mysql://root:{pwd}@localhost:3306/stock_data"
# engine = create_engine(string)
# # Establish a connection to the local DB
# conn = engine.connect()
# # Import and establish Base for which classes will be constructed
# from sqlalchemy.ext.declarative import declarative_base
# Base = declarative_base()
# # Import modules to declare columns and column data types
# from sqlalchemy import Column, Integer, String, Float

In [31]:
#   class sector_yony_dividend (Base):
#     __tablename__ = 'EBITA_current_price'
#     symbol = Column("symbol",String(100),primary_key=True)
#     value = Column("current_price",Float)

In [32]:
# # Create both the company_diversity_m_f and company_diversity_race tables within the database
# Base.metadata.create_all(conn)
# # confirming that tables got created in the DB
# engine.table_names()
# # Create a session that binds to the engine to enable insert of data
# session = Session(bind=engine)

In [33]:
# frame_to_push.to_sql(name="EBITA_current_price", con=engine, if_exists='append',index=False)

In [34]:
# EBITA_current_price = pd.read_sql("select * from EBITA_current_price", con=engine)

In [35]:
# EBITA_current_price.to_excel("current_price.xlsx")

In [36]:
EBITA_current_price = pd.read_excel("current_price.xlsx")

In [37]:
df3 = df2.merge(EBITA_current_price,on="symbol")

In [38]:
df3

,index,security,symbol,sec_filing,gics_sector,gics_sub_industry,hq_location,date_added,cik,year_founded,model,ebita_multiple,sub_industry_average,percent_change,current_price
0,1,3M Company,MMM,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902,EBITDA_Multiple,15.48,15.850000,2.390181,203.21
1,216,General Electric,GE,reports,Industrials,Industrial Conglomerates,"Boston, Massachusetts",NaN,40545,1892,EBITDA_Multiple,12.68,15.850000,25.000000,9.88
2,242,Honeywell Int'l Inc.,HON,reports,Industrials,Industrial Conglomerates,"Morristown, New Jersey",1964-03-31,773840,1906,EBITDA_Multiple,13.29,15.850000,19.262603,155.93
3,407,Roper Technologies,ROP,reports,Industrials,Industrial Conglomerates,"Sarasota, Florida",2009-12-23,882835,NaN,EBITDA_Multiple,21.95,15.850000,-27.790433,330.98
4,2,Abbott Laboratories,ABT,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888,EBITDA_Multiple,21.20,24.537368,15.742304,78.23
5,4,ABIOMED Inc,ABMD,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981,EBITDA_Multiple,64.16,24.537368,-61.755972,313.22
6,13,Agilent Technologies Inc,A,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999,EBITDA_Multiple,20.67,24.537368,18.710055,79.52
7,69,Baxter International Inc.,BAX,reports,Health Care,Health Care Equipment,"Deerfield, Illinois",1972-09-30,10456,1931,EBITDA_Multiple,16.04,24.537368,52.976112,77.63
8,71,Becton Dickinson,BDX,reports,Health Care,Health Care Equipment,"Franklin Lakes, New Jersey",1972-09-30,10795,1897,EBITDA_Multiple,16.67,24.537368,47.194772,241.25
9,81,Boston Scientific,BSX,reports,Health Care,Health Care Equipment,"Marlborough, Massachusetts[6]",1995-02-24,885725,NaN,EBITDA_Multiple,22.40,24.537368,9.541823,37.64
10,144,Danaher Corp.,DHR,reports,Health Care,Health Care Equipment,"Washington, D.C.",NaN,313616,1969,EBITDA_Multiple,20.75,24.537368,18.252378,129.46
11,172,Edwards Lifesciences,EW,reports,Health Care,Health Care Equipment,"Irvine, California",2011-04-01,1099800,NaN,EBITDA_Multiple,33.83,24.537368,-27.468612,189.40
12,240,Hologic,HOLX,reports,Health Care,Health Care Equipment,"Marlborough, Massachusetts",2016-03-30,859737,NaN,EBITDA_Multiple,15.05,24.537368,63.038993,46.81
13,249,IDEXX Laboratories,IDXX,reports,Health Care,Health Care Equipment,"Westbrook, Maine",2017-01-05,874716,NaN,EBITDA_Multiple,34.22,24.537368,-28.295241,219.24
14,262,Intuitive Surgical Inc.,ISRG,reports,Health Care,Health Care Equipment,"Sunnyvale, California",2008-06-02,1035267,NaN,EBITDA_Multiple,44.85,24.537368,-45.290148,562.72
15,317,Medtronic plc,MDT,reports,Health Care,Health Care Equipment,"Dublin, Ireland",1986-10-31,64670,NaN,EBITDA_Multiple,14.18,24.537368,73.042090,90.62
16,371,PerkinElmer,PKI,reports,Health Care,Health Care Equipment,"Waltham, Massachusetts",1985-05-31,31791,NaN,EBITDA_Multiple,21.65,24.537368,13.336575,94.53
17,403,ResMed,RMD,reports,Health Care,Health Care Equipment,"San Diego, California",2017-07-26,943819,NaN,EBITDA_Multiple,20.91,24.537368,17.347530,101.42
18,427,Stryker Corp.,SYK,reports,Health Care,Health Care Equipment,"Kalamazoo, Michigan",2000-12-12,310764,NaN,EBITDA_Multiple,20.60,24.537368,19.113439,195.17
19,440,Teleflex Inc,TFX,reports,Health Care,Health Care Equipment,"Wayne, Pennsylvania",2019-01-18,96943,1943,EBITDA_Multiple,23.52,24.537368,4.325546,299.59
20,443,Thermo Fisher Scientific,TMO,reports,Health Care,Health Care Equipment,"Waltham, Massachusetts",NaN,97745,2006,EBITDA_Multiple,19.86,24.537368,23.551704,268.80
21,471,Varian Medical Systems,VAR,reports,Health Care,Health Care Equipment,"Palo Alto, California",2007-02-12,203527,NaN,EBITDA_Multiple,21.24,24.537368,15.524333,138.71
22,503,Zimmer Biomet Holdings,ZBH,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN,EBITDA_Multiple,14.41,24.537368,70.280142,126.59
23,3,AbbVie Inc.,ABBV,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),EBITDA_Multiple,10.96,12.915000,17.837591,79.51
24,22,"Allergan, Plc",AGN,reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983,EBITDA_Multiple,10.04,12.915000,28.635458,146.34
25,272,Johnson & Johnson,JNJ,reports,Health Care,Pharmaceuticals,"New Brunswick, New Jersey",1973-06-30,200406,1886,EBITDA_Multiple,13.24,12.915000,-2.454683,136.61
26,294,Lilly (Eli) & Co.,LLY,reports,Health Care,Pharmaceuticals,"Indianapolis, Indiana",1970-12-31,59478,1876,EBITDA_Multiple,17.61,12.915000,-26.660988,129.87
27,318,Merck & Co.,MRK,reports,Health Care,Pharmaceuticals,"Whitehouse Station, New Jersey",NaN,310158,1891,EBITDA_Multiple,17.48,12.915000,-26.115561,82.35
28,335,Mylan N.V.,MYL,reports,Health Care,Pharmaceuticals,"Amsterdam, Netherlands",2004-04-23,69499,NaN,EBITDA_Multiple,7.83,12.915000,64.942529,28.32
29,338,Nektar Therapeutics,NKTR,reports,Health Care,Pharmaceuticals,"San Francisco, California",2018-03-19,906709,NaN,EBITDA_Multiple,6.46,12.915000,99.922601,32.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,326,Mohawk Industries,MHK,reports,Consumer Discretionary,Home Furnishings,"Amsterdam, New York",2013-12-23,851968,NaN,EBITDA_Multiple,7.11,8.995000,26.511955,124.75
476,297,LKQ Corporation,LKQ,reports,Consumer Discretionary,Distributors,"Chicago, Illinois",2016-05-23,1065696,NaN,EBITDA_Multiple,10.47,10.470000,0.000000,28.34
477,304,Macy's Inc.,M,reports,Consumer Discretionary,Department Stores,"Cincinnati, Ohio",NaN,794367,1929,EBITDA_Multiple,4.33,4.820000,11.316397,23.86
478,350,Nordstrom,JWN,reports,Consumer Discretionary,Department Stores,"Seattle, Washington",1986-08-31,72333,NaN,EBITDA_Multiple,5.31,4.820000,-9.227872,43.54
479,309,Martin Marietta Materials,MLM,reports,Materials,Construction Materials,"Raleigh, North Carolina",2014-07-02,916076,NaN,EBITDA_Multiple,14.36,15.115000,5.257660,196.43
480,480,Vulcan Materials,VMC,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN,EBITDA_Multiple,15.87,15.115000,-4.757404,114.99
481,321,MGM Resorts International,MGM,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2017-07-26,789570,NaN,EBITDA_Multiple,12.63,11.710000,-7.284244,25.75
482,497,Wynn Resorts Ltd,WYNN,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN,EBITDA_Multiple,10.79,11.710000,8.526413,116.45
483,327,Molson Coors Brewing Company,TAP,reports,Consumer Staples,Brewers,"Denver, Colorado",1976-06-30,24545,NaN,EBITDA_Multiple,9.83,9.830000,0.000000,58.75
484,340,Netflix Inc.,NFLX,reports,FAANG,Communication Services__Movies & Entertainment,"Los Gatos, California",2010-12-20,1065280,1997,EBITDA_Multiple,97.24,97.240000,0.000000,366.23
485,341,Newell Brands,NWL,reports,Consumer Discretionary,Housewares & Specialties,"Sandy Springs, Georgia",1989-04-30,814453,NaN,EBITDA_Multiple,14.05,14.050000,0.000000,15.07
486,342,Newmont Mining Corporation,NEM,reports,Materials,Gold,"Denver, Colorado",1969-06-30,1164727,1921,EBITDA_Multiple,7.38,7.380000,0.000000,34.90
487,343,News Corp. Class A,NWSA,reports,Communication Services,Publishing,"New York, New York",2013-08-01,1564708,NaN,EBITDA_Multiple,8.11,8.110000,0.000000,12.56
488,344,News Corp. Class B,NWS,reports,Communication Services,Publishing,"New York, New York",2015-09-18,1564708,NaN,EBITDA_Multiple,8.11,8.110000,0.000000,12.59
489,356,Nucor Corp.,NUE,reports,Materials,Steel,"Charlotte, North Carolina",1985-04-30,73309,NaN,EBITDA_Multiple,5.03,5.030000,0.000000,56.88
490,369,People's United Financial,PBCT,reports,Financials,Thrifts & Mortgage Finance,"Bridgeport, Connecticut",2008-11-13,1378946,NaN,EBITDA_Multiple,NaN,NaN,NaN,15.84
491,402,Republic Services Inc,RSG,reports,Industrials,Environmental & Facilities Services,"Phoenix, Arizona",2008-12-05,1060391,NaN,EBITDA_Multiple,12.05,20.166667,67.358230,79.43
492,406,Rollins Inc.,ROL,reports,Industrials,Environmental & Facilities Services,"Atlanta, Georgia",2018-10-01,84839,NaN,EBITDA_Multiple,35.03,20.166667,-42.430298,40.57
493,484,Waste Management Inc.,WM,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968,EBITDA_Multiple,13.42,20.166667,50.273224,102.18
494,404,Robert Half International,RHI,reports,Industrials,Human Resource & Employment Services,"Menlo Park, California",2000-12-05,315213,NaN,EBITDA_Multiple,11.00,11.000000,0.000000,63.15
495,433,Sysco Corp.,SYY,reports,Consumer Staples,Food Distributors,"Houston, Texas",1986-12-31,96021,NaN,EBITDA_Multiple,12.59,12.590000,0.000000,66.20
496,445,"Twitter, Inc.",TWTR,reports,Communication Services,Interactive Media & Services,"San Francisco, California",2018-06-07,1418091,NaN,EBITDA_Multiple,28.21,27.655000,-1.967387,32.59
497,452,TripAdvisor,TRIP,reports,Communication Services,Interactive Media & Services,"Newton, Massachusetts",2011-12-21,1526520,NaN,EBITDA_Multiple,27.10,27.655000,2.047970,50.78
498,453,Twenty-First Century Fox Class A,FOXA,reports,Communication Services,Movies & Entertainment,"New York, New York",2013-07-01,1308161,NaN,EBITDA_Multiple,NaN,8.350000,NaN,37.44
499,454,Twenty-First Century Fox Class B,FOX,reports,Communication Services,Movies & Entertainment,"New York, New York",2015-09-18,1308161,NaN,EBITDA_Multiple,NaN,8.350000,NaN,36.45
500,477,Viacom Inc.,VIAB,reports,Communication Services,Movies & Entertainment,"New York, New York",NaN,1339947,NaN,EBITDA_Multiple,6.23,8.350000,34.028892,26.32
501,483,The Walt Disney Company,DIS,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN,EBITDA_Multiple,10.47,8.350000,-20.248329,107.79
502,465,"United Rentals, Inc.",URI,reports,Industrials,Trading Companies & Distributors,"Stamford, Connecticut",2014-09-20,1067701,NaN,EBITDA_Multiple,8.59,8.590000,0.000000,111.12
503,482,Walgreens Boots Alliance,WBA,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,NaN,EBITDA_Multiple,9.47,9.470000,0.000000,61.69
504,494,Whirlpool Corp.,WHR,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911,EBITDA_Multiple,7.16,7.160000,0.000000,129.07

In [39]:
df3["target_price"] = (df3['current_price']*(df3["percent_change"]/100)) + df3['current_price']

In [40]:
df3

,index,security,symbol,sec_filing,gics_sector,gics_sub_industry,hq_location,date_added,cik,year_founded,model,ebita_multiple,sub_industry_average,percent_change,current_price,target_price
0,1,3M Company,MMM,reports,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",NaN,66740,1902,EBITDA_Multiple,15.48,15.850000,2.390181,203.21,208.067087
1,216,General Electric,GE,reports,Industrials,Industrial Conglomerates,"Boston, Massachusetts",NaN,40545,1892,EBITDA_Multiple,12.68,15.850000,25.000000,9.88,12.350000
2,242,Honeywell Int'l Inc.,HON,reports,Industrials,Industrial Conglomerates,"Morristown, New Jersey",1964-03-31,773840,1906,EBITDA_Multiple,13.29,15.850000,19.262603,155.93,185.966178
3,407,Roper Technologies,ROP,reports,Industrials,Industrial Conglomerates,"Sarasota, Florida",2009-12-23,882835,NaN,EBITDA_Multiple,21.95,15.850000,-27.790433,330.98,238.999226
4,2,Abbott Laboratories,ABT,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888,EBITDA_Multiple,21.20,24.537368,15.742304,78.23,90.545204
5,4,ABIOMED Inc,ABMD,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981,EBITDA_Multiple,64.16,24.537368,-61.755972,313.22,119.787945
6,13,Agilent Technologies Inc,A,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999,EBITDA_Multiple,20.67,24.537368,18.710055,79.52,94.398236
7,69,Baxter International Inc.,BAX,reports,Health Care,Health Care Equipment,"Deerfield, Illinois",1972-09-30,10456,1931,EBITDA_Multiple,16.04,24.537368,52.976112,77.63,118.755356
8,71,Becton Dickinson,BDX,reports,Health Care,Health Care Equipment,"Franklin Lakes, New Jersey",1972-09-30,10795,1897,EBITDA_Multiple,16.67,24.537368,47.194772,241.25,355.107386
9,81,Boston Scientific,BSX,reports,Health Care,Health Care Equipment,"Marlborough, Massachusetts[6]",1995-02-24,885725,NaN,EBITDA_Multiple,22.40,24.537368,9.541823,37.64,41.231542
10,144,Danaher Corp.,DHR,reports,Health Care,Health Care Equipment,"Washington, D.C.",NaN,313616,1969,EBITDA_Multiple,20.75,24.537368,18.252378,129.46,153.089528
11,172,Edwards Lifesciences,EW,reports,Health Care,Health Care Equipment,"Irvine, California",2011-04-01,1099800,NaN,EBITDA_Multiple,33.83,24.537368,-27.468612,189.40,137.374448
12,240,Hologic,HOLX,reports,Health Care,Health Care Equipment,"Marlborough, Massachusetts",2016-03-30,859737,NaN,EBITDA_Multiple,15.05,24.537368,63.038993,46.81,76.318553
13,249,IDEXX Laboratories,IDXX,reports,Health Care,Health Care Equipment,"Westbrook, Maine",2017-01-05,874716,NaN,EBITDA_Multiple,34.22,24.537368,-28.295241,219.24,157.205513
14,262,Intuitive Surgical Inc.,ISRG,reports,Health Care,Health Care Equipment,"Sunnyvale, California",2008-06-02,1035267,NaN,EBITDA_Multiple,44.85,24.537368,-45.290148,562.72,307.863277
15,317,Medtronic plc,MDT,reports,Health Care,Health Care Equipment,"Dublin, Ireland",1986-10-31,64670,NaN,EBITDA_Multiple,14.18,24.537368,73.042090,90.62,156.810742
16,371,PerkinElmer,PKI,reports,Health Care,Health Care Equipment,"Waltham, Massachusetts",1985-05-31,31791,NaN,EBITDA_Multiple,21.65,24.537368,13.336575,94.53,107.137064
17,403,ResMed,RMD,reports,Health Care,Health Care Equipment,"San Diego, California",2017-07-26,943819,NaN,EBITDA_Multiple,20.91,24.537368,17.347530,101.42,119.013864
18,427,Stryker Corp.,SYK,reports,Health Care,Health Care Equipment,"Kalamazoo, Michigan",2000-12-12,310764,NaN,EBITDA_Multiple,20.60,24.537368,19.113439,195.17,232.473699
19,440,Teleflex Inc,TFX,reports,Health Care,Health Care Equipment,"Wayne, Pennsylvania",2019-01-18,96943,1943,EBITDA_Multiple,23.52,24.537368,4.325546,299.59,312.548903
20,443,Thermo Fisher Scientific,TMO,reports,Health Care,Health Care Equipment,"Waltham, Massachusetts",NaN,97745,2006,EBITDA_Multiple,19.86,24.537368,23.551704,268.80,332.106980
21,471,Varian Medical Systems,VAR,reports,Health Care,Health Care Equipment,"Palo Alto, California",2007-02-12,203527,NaN,EBITDA_Multiple,21.24,24.537368,15.524333,138.71,160.243803
22,503,Zimmer Biomet Holdings,ZBH,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,NaN,EBITDA_Multiple,14.41,24.537368,70.280142,126.59,215.557631
23,3,AbbVie Inc.,ABBV,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),EBITDA_Multiple,10.96,12.915000,17.837591,79.51,93.692669
24,22,"Allergan, Plc",AGN,reports,Health Care,Pharmaceuticals,"Dublin, Ireland",1999-04-12,1578845,1983,EBITDA_Multiple,10.04,12.915000,28.635458,146.34,188.245129
25,272,Johnson & Johnson,JNJ,reports,Health Care,Pharmaceuticals,"New Brunswick, New Jersey",1973-06-30,200406,1886,EBITDA_Multiple,13.24,12.915000,-2.454683,136.61,133.256658
26,294,Lilly (Eli) & Co.,LLY,reports,Health Care,Pharmaceuticals,"Indianapolis, Indiana",1970-12-31,59478,1876,EBITDA_Multiple,17.61,12.915000,-26.660988,129.87,95.245375
27,318,Merck & Co.,MRK,reports,Health Care,Pharmaceuticals,"Whitehouse Station, New Jersey",NaN,310158,1891,EBITDA_Multiple,17.48,12.915000,-26.115561,82.35,60.843836
28,335,Mylan N.V.,MYL,reports,Health Care,Pharmaceuticals,"Amsterdam, Netherlands",2004-04-23,69499,NaN,EBITDA_Multiple,7.83,12.915000,64.942529,28.32,46.711724
29,338,Nektar Therapeutics,NKTR,reports,Health Care,Pharmaceuticals,"San Francisco, California",2018-03-19,906709,NaN,EBITDA_Multiple,6.46,12.915000,99.922601,32.37,64.714946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,326,Mohawk Industries,MHK,reports,Consumer Discretionary,Home Furnishings,"Amsterdam, New York",2013-12-23,851968,NaN,EBITDA_Multiple,7.11,8.995000,26.511955,124.75,157.823664
476,297,LKQ Corporation,LKQ,reports,Consumer Discretionary,Distributors,"Chicago, Illinois",2016-05-23,1065696,NaN,EBITDA_Multiple,10.47,10.470000,0.000000,28.34,28.340000
477,304,Macy's Inc.,M,reports,Consumer Discretionary,Department Stores,"Cincinnati, Ohio",NaN,794367,1929,EBITDA_Multiple,4.33,4.820000,11.316397,23.86,26.560092
478,350,Nordstrom,JWN,reports,Consumer Discretionary,Department Stores,"Seattle, Washington",1986-08-31,72333,NaN,EBITDA_Multiple,5.31,4.820000,-9.227872,43.54,39.522185
479,309,Martin Marietta Materials,MLM,reports,Materials,Construction Materials,"Raleigh, North Carolina",2014-07-02,916076,NaN,EBITDA_Multiple,14.36,15.115000,5.257660,196.43,206.757622
480,480,Vulcan Materials,VMC,reports,Materials,Construction Materials,"Birmingham, Alabama",1999-06-30,1396009,NaN,EBITDA_Multiple,15.87,15.115000,-4.757404,114.99,109.519461
481,321,MGM Resorts International,MGM,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2017-07-26,789570,NaN,EBITDA_Multiple,12.63,11.710000,-7.284244,25.75,23.874307
482,497,Wynn Resorts Ltd,WYNN,reports,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,NaN,EBITDA_Multiple,10.79,11.710000,8.526413,116.45,126.379008
483,327,Molson Coors Brewing Company,TAP,reports,Consumer Staples,Brewers,"Denver, Colorado",1976-06-30,24545,NaN,EBITDA_Multiple,9.83,9.830000,0.000000,58.75,58.750000
484,340,Netflix Inc.,NFLX,reports,FAANG,Communication Services__Movies & Entertainment,"Los Gatos, California",2010-12-20,1065280,1997,EBITDA_Multiple,97.24,97.240000,0.000000,366.23,366.230000
485,341,Newell Brands,NWL,reports,Consumer Discretionary,Housewares & Specialties,"Sandy Springs, Georgia",1989-04-30,814453,NaN,EBITDA_Multiple,14.05,14.050000,0.000000,15.07,15.070000
486,342,Newmont Mining Corporation,NEM,reports,Materials,Gold,"Denver, Colorado",1969-06-30,1164727,1921,EBITDA_Multiple,7.38,7.380000,0.000000,34.90,34.900000
487,343,News Corp. Class A,NWSA,reports,Communication Services,Publishing,"New York, New York",2013-08-01,1564708,NaN,EBITDA_Multiple,8.11,8.110000,0.000000,12.56,12.560000
488,344,News Corp. Class B,NWS,reports,Communication Services,Publishing,"New York, New York",2015-09-18,1564708,NaN,EBITDA_Multiple,8.11,8.110000,0.000000,12.59,12.590000
489,356,Nucor Corp.,NUE,reports,Materials,Steel,"Charlotte, North Carolina",1985-04-30,73309,NaN,EBITDA_Multiple,5.03,5.030000,0.000000,56.88,56.880000
490,369,People's United Financial,PBCT,reports,Financials,Thrifts & Mortgage Finance,"Bridgeport, Connecticut",2008-11-13,1378946,NaN,EBITDA_Multiple,NaN,NaN,NaN,15.84,NaN
491,402,Republic Services Inc,RSG,reports,Industrials,Environmental & Facilities Services,"Phoenix, Arizona",2008-12-05,1060391,NaN,EBITDA_Multiple,12.05,20.166667,67.358230,79.43,132.932642
492,406,Rollins Inc.,ROL,reports,Industrials,Environmental & Facilities Services,"Atlanta, Georgia",2018-10-01,84839,NaN,EBITDA_Multiple,35.03,20.166667,-42.430298,40.57,23.356028
493,484,Waste Management Inc.,WM,reports,Industrials,Environmental & Facilities Services,"Houston, Texas",NaN,823768,1968,EBITDA_Multiple,13.42,20.166667,50.273224,102.18,153.549180
494,404,Robert Half International,RHI,reports,Industrials,Human Resource & Employment Services,"Menlo Park, California",2000-12-05,315213,NaN,EBITDA_Multiple,11.00,11.000000,0.000000,63.15,63.150000
495,433,Sysco Corp.,SYY,reports,Consumer Staples,Food Distributors,"Houston, Texas",1986-12-31,96021,NaN,EBITDA_Multiple,12.59,12.590000,0.000000,66.20,66.200000
496,445,"Twitter, Inc.",TWTR,reports,Communication Services,Interactive Media & Services,"San Francisco, California",2018-06-07,1418091,NaN,EBITDA_Multiple,28.21,27.655000,-1.967387,32.59,31.948828
497,452,TripAdvisor,TRIP,reports,Communication Services,Interactive Media & Services,"Newton, Massachusetts",2011-12-21,1526520,NaN,EBITDA_Multiple,27.10,27.655000,2.047970,50.78,51.819959
498,453,Twenty-First Century Fox Class A,FOXA,reports,Communication Services,Movies & Entertainment,"New York, New York",2013-07-01,1308161,NaN,EBITDA_Multiple,NaN,8.350000,NaN,37.44,NaN
499,454,Twenty-First Century Fox Class B,FOX,reports,Communication Services,Movies & Entertainment,"New York, New York",2015-09-18,1308161,NaN,EBITDA_Multiple,NaN,8.350000,NaN,36.45,NaN
500,477,Viacom Inc.,VIAB,reports,Communication Services,Movies & Entertainment,"New York, New York",NaN,1339947,NaN,EBITDA_Multiple,6.23,8.350000,34.028892,26.32,35.276404
501,483,The Walt Disney Company,DIS,reports,Communication Services,Movies & Entertainment,"Burbank, California",1976-06-30,1001039,NaN,EBITDA_Multiple,10.47,8.350000,-20.248329,107.79,85.964327
502,465,"United Rentals, Inc.",URI,reports,Industrials,Trading Companies & Distributors,"Stamford, Connecticut",2014-09-20,1067701,NaN,EBITDA_Multiple,8.59,8.590000,0.000000,111.12,111.120000
503,482,Walgreens Boots Alliance,WBA,reports,Consumer Staples,Drug Retail,"Deerfield, Illinois",1979-12-31,1618921,NaN,EBITDA_Multiple,9.47,9.470000,0.000000,61.69,61.690000
504,494,Whirlpool Corp.,WHR,reports,Consumer Discretionary,Household Appliances,"Benton Harbor, Michigan",NaN,106640,1911,EBITDA_Multiple,7.16,7.160000,0.000000,129.07,129.070000

In [41]:
df3.to_excel("FULL_table.xlsx")

In [42]:
final =df3[["symbol","gics_sector","gics_sub_industry","model","percent_change","current_price","target_price"]]

In [43]:
final.to_excel("final_table.xlsx")

In [44]:
final_frame = pd.read_excel('final_table.xlsx')

In [45]:
# final_frame["percent_change"] = (1 - final_frame["percent_change"]) * 100

In [46]:
final_frame.to_excel("Ebitda_final_table_percent.xlsx")