In [1]:
# remove the first k!! find NFX NWS FOX UA

In [2]:
# Import Dependencies 
import pandas as pd
pwd = "Welcome123"
from sqlalchemy import create_engine
import pymysql
import warnings
warnings.filterwarnings('ignore')
from sqlalchemy.orm import Session
from splinter import Browser
from bs4 import BeautifulSoup as bs
import requests
import shutil
import re
import numpy as np

In [3]:
# Setup Pymysql and connect to AWS MySQL workbench
pymysql.install_as_MySQLdb() 
string = f"mysql://ucbx:{pwd}@stock-data-analysis.ciuxgx1cjbsw.us-east-2.rds.amazonaws.com/stock_data"
engine = create_engine(string)
# Establish a connection to the local DB
conn = engine.connect()

In [4]:
# # Setup Pymysql and connect to local MySQL workbench
# rds_connection_string = "root:Cocascalvo1@127.0.0.1/wiki_db"
# engine = create_engine(f'mysql://{rds_connection_string}')
# conn = engine.connect()

In [9]:
# Create list of stocks for iteration 
stock = pd.read_sql('SELECT * FROM stock_data.ev_sales_multiple;', con=conn)

# stock_list = stock['Symbol'].tolist()
stock.head()
# stock

,symbol,gics_sector,gics_sub_industry,model,percent_change,current_price,target_price
0,A,Health Care,Health Care Equipment,ev_sales_multiple,1.74036,64.79,65.9176
1,AAL,Industrials,Airlines,ev_sales_multiple,404.04400,32.11,161.8480
2,AAP,Consumer Discretionary,Automotive Retail,ev_sales_multiple,54.42860,155.46,240.0750
3,AAPL,Information Technology,"Technology Hardware, Storage & Peripherals",ev_sales_multiple,8.90164,225.74,245.8350
4,ABBV,Health Care,Pharmaceuticals,ev_sales_multiple,-24.03200,92.19,70.0349

In [10]:
# Create list of stocks for iteration 
desc = pd.read_sql('SELECT * FROM stock_data.descriptions;', con=conn)

# stock_list = stock['Symbol'].tolist()
desc.head()
# stock

  symbol                                        description
0    MMM  3M Company operates as a technology company wo...
1    ABT  Abbott Laboratories discovers, develops, manuf...
2   ABBV  AbbVie Inc. discovers, develops, manufactures,...
3   ABMD  ABIOMED, Inc. engages in the research, develop...
4    ACN  Accenture plc provides consulting, technology,...

In [11]:
result = pd.merge(stock, desc, on=['symbol'])
result.head()

,symbol,gics_sector,gics_sub_industry,model,percent_change,current_price,target_price,description
0,A,Health Care,Health Care Equipment,ev_sales_multiple,1.74036,64.79,65.9176,"Agilent Technologies, Inc. provides applicatio..."
1,AAL,Industrials,Airlines,ev_sales_multiple,404.04400,32.11,161.8480,"American Airlines Group Inc., through its subs..."
2,AAP,Consumer Discretionary,Automotive Retail,ev_sales_multiple,54.42860,155.46,240.0750,"Advance Auto Parts, Inc. provides automotive r..."
3,AAPL,Information Technology,"Technology Hardware, Storage & Peripherals",ev_sales_multiple,8.90164,225.74,245.8350,"Apple Inc. designs, manufactures, and markets ..."
4,ABBV,Health Care,Pharmaceuticals,ev_sales_multiple,-24.03200,92.19,70.0349,"AbbVie Inc. discovers, develops, manufactures,..."

In [12]:
result.to_sql(name='ev_sales_multiple', con=engine, if_exists='append', index=False)

InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'description' in 'field list'") [SQL: 'INSERT INTO ev_sales_multiple (symbol, gics_sector, gics_sub_industry, model, percent_change, current_price, target_price, description) VALUES (%(symbol)s, %(gics_sector)s, %(gics_sub_industry)s, %(model)s, %(percent_change)s, %(current_price)s, %(target_price)s, %(description)s)'] [parameters: ({'symbol': 'A', 'gics_sector': 'Health Care', 'gics_sub_industry': 'Health Care Equipment', 'model': 'ev_sales_multiple', 'percent_change': 1.74036, 'current_price': 64.79, 'target_price': 65.9176, 'description': "Agilent Technologies, Inc. provides application focused solutions to the life sciences, diagnostics, and applied chemical markets worldwide. It opera ... (1689 characters truncated) ... ufacturer's representatives, and electronic commerce. Agilent Technologies, Inc. was founded in 1999 and is headquartered in Santa Clara, California."}, {'symbol': 'AAL', 'gics_sector': 'Industrials', 'gics_sub_industry': 'Airlines', 'model': 'ev_sales_multiple', 'percent_change': 404.044, 'current_price': 32.11, 'target_price': 161.848, 'description': 'American Airlines Group Inc., through its subsidiaries, operates as a network air carrier. It provides scheduled air transportation services for pass ... (378 characters truncated) ... ts name to American Airlines Group Inc. in December 2013. American Airlines Group Inc. was founded in 1934 and is headquartered in Fort Worth, Texas.'}, {'symbol': 'AAP', 'gics_sector': 'Consumer Discretionary', 'gics_sub_industry': 'Automotive Retail', 'model': 'ev_sales_multiple', 'percent_change': 54.4286, 'current_price': 155.46, 'target_price': 240.075, 'description': 'Advance Auto Parts, Inc. provides automotive replacement parts, accessories, batteries, and maintenance items for domestic and imported cars, vans, s ... (1676 characters truncated) ... nd Caicos, the British Virgin Islands, and the Pacific Islands. Advance Auto Parts, Inc. was founded in 1929 and is based in Raleigh, North Carolina.'}, {'symbol': 'AAPL', 'gics_sector': 'Information Technology', 'gics_sub_industry': 'Technology Hardware, Storage & Peripherals', 'model': 'ev_sales_multiple', 'percent_change': 8.90164, 'current_price': 225.74, 'target_price': 245.835, 'description': "Apple Inc. designs, manufactures, and markets mobile communication and media devices, and personal computers. It also sells various related software, ... (1374 characters truncated) ... party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California."}, {'symbol': 'ABBV', 'gics_sector': 'Health Care', 'gics_sub_industry': 'Pharmaceuticals', 'model': 'ev_sales_multiple', 'percent_change': -24.032, 'current_price': 92.19, 'target_price': 70.0349, 'description': "AbbVie Inc. discovers, develops, manufactures, and sells pharmaceutical products worldwide. The company offers HUMIRA, a therapy administered as an i ... (1679 characters truncated) ... ny; Voluntis; Tizona Therapeutics, Inc.; and Voyager Therapeutics, Inc. The company was incorporated in 2012 and is based in North Chicago, Illinois."}, {'symbol': 'ABC', 'gics_sector': 'Health Care', 'gics_sub_industry': 'Health Care Distributors', 'model': 'ev_sales_multiple', 'percent_change': 3430.38, 'current_price': 92.22, 'target_price': 3255.72, 'description': "AmerisourceBergen Corporation sources and distributes pharmaceutical products in the United States and internationally. Its Pharmaceutical Distributi ... (1601 characters truncated) ... creating sales force services to manufacturers. AmerisourceBergen Corporation was founded in 1985 and is headquartered in Chesterbrook, Pennsylvania."}, {'symbol': 'ABT', 'gics_sector': 'Health Care', 'gics_sub_industry': 'Health Care Equipment', 'model': 'ev_sales_multiple', 'percent_change': -11.4435, 'current_price': 72.33, 'target_price': 64.0529, 'description': "Abbott Laboratories discovers, develops, manufactures, and sells health care products worldwide. The company's Established Pharmaceutical Products se ... (1688 characters truncated) ... anagement decision software, and accessories for people with diabetes. The company was founded in 1888 and is headquartered in Abbott Park, Illinois."}, {'symbol': 'ACN', 'gics_sector': 'Information Technology', 'gics_sub_industry': 'IT Consulting & Other Services', 'model': 'ev_sales_multiple', 'percent_change': 77.8175, 'current_price': 169.07, 'target_price': 300.636, 'description': "Accenture plc provides consulting, technology, and outsourcing services in Ireland and internationally. Its Communications, Media & Technology segmen ... (1685 characters truncated) ... egrate digital technologies. Accenture plc has a strategic alliance with Quantexa. Accenture plc was founded in 1989 and is based in Dublin, Ireland."}  ... displaying 10 of 414 total bound parameter sets ...  {'symbol': 'XOM', 'gics_sector': 'Energy', 'gics_sub_industry': 'Integrated Oil & Gas', 'model': 'ev_sales_multiple', 'percent_change': 123.478, 'current_price': 68.19, 'target_price': 152.39, 'description': 'Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States, Canada/Other Americas, Europe, Africa, Asia, and Au ... (398 characters truncated) ... et operated wells with proved reserves of 24.3 billion oil-equivalent barrels. The company was founded in 1870 and is headquartered in Irving, Texas.'}, {'symbol': 'XRAY', 'gics_sector': 'Health Care', 'gics_sub_industry': 'Health Care Supplies', 'model': 'ev_sales_multiple', 'percent_change': 60.8731, 'current_price': 37.21, 'target_price': 59.8609, 'description': 'DENTSPLY SIRONA Inc. designs, develops, manufactures, and markets various dental and oral health products, and other consumable healthcare products p ... (1581 characters truncated) ... . and changed its name to DENTSPLY SIRONA Inc. in February 2016. DENTSPLY SIRONA Inc. was founded in 1899 and is headquartered in York, Pennsylvania.'})] (Background on this error at: http://sqlalche.me/e/2j85)

In [3]:
# # Open browser for webscrape
# executable_path = {"executable_path": "/usr/local/bin/chromedriver"}
# browser = Browser("chrome", **executable_path, headless=False)

In [34]:
# Scrape for stock descriptions
# TEST
# stock_list = []
# description_list = []

# for stock in stock_list:
#     url = f"https://www.marketbeat.com/stocks/NYSE/{stock}/"
#     browser.visit(url)
#     html = browser.html
#     soup = bs(html, 'html.parser')
#     full  = soup.find("div", class_="tab-pane active").find('div').text
# #     finished = re.match(r'(?:[^.:;]+[.:;]){}', full).group()

#     description_list.append(full)

In [62]:
# Put Descriptions into a dataframe and merge with Symbols
# description_list = pd.DataFrame(description_list)
# description_list = description_list.rename(columns={0:"description"})
# description_list = description_list.reset_index()

# stock_list = pd.DataFrame(stock_list)
# stock_list = stock_list.rename(columns={0:"symbol"})
# stock_list = stock_list.reset_index()

# # Merge descriptions to dataframe
# result = pd.merge(stock_list, description_list, on=['index'])
# result.head()

In [63]:
# Push Descriptions dataframe to MySQL
# result.to_sql(name='descriptions', con=engine, if_exists='append', index=False)

In [64]:
# # Iterate through list of stocks
# # TEST  #stock_list = ["TJX","AMT","MSFT"]

# Create list to append scrape data to
# stock_price = []
# stock_PE = []
# stock_eps = []
    
# # # Scrape for Stock Price
# for stock in stock_list:
#     try:
#         url = f"https://www.marketbeat.com/stocks/NYSE/{stock}/"
#         browser.visit(url)
#         html = browser.html
#         soup = bs(html, 'html.parser')
#         full = soup.find("div", class_="col-md-3 price").text
#         parsed_1 = re.sub('[\ ]', ',', full)
#         parsed_2 = parsed_1[:9]
#         parsed_3 = re.sub('[\,-]', '', parsed_2)
#         parsed_4 = re.sub('[\$,]', '', parsed_3)
#         parsed_5 = re.sub('[\+]', '', parsed_4)
#         finished = float(parsed_5)
#     except:
#         url = f"https://www.marketbeat.com/stocks/NYSE/{stock}/"
#         browser.visit(url)
#         html = browser.html
#         soup = bs(html, 'html.parser')
#         price = soup.find("div", class_="col-md-3 price").text
#         full = re.sub('[\ ]', ',', price)
#         parsed_1 = full[:9]
#         parsed_2 = re.sub('[\,-]', '',parsed_1)
#         parsed_3 = re.sub('[\$,]', '', parsed_2)
#         parsed_4 = re.sub('[\+]', '', parsed_3)
#         parsed_5 = parsed_4[:4]
#         finished = float(parsed_5)
#     stock_price.append(finished)
    
#     try:
#         # Scrape for PE Ratio
#         symbol  = soup.find("div", class_="col-md-9 price-data-section").find_all('strong')
#         data_str = str(symbol)
#         b_soup = bs(data_str)
#         data_text = b_soup.get_text()
#         result = [x.strip() for x in data_text.split(' ')]
#         parsed_1 = result[-3]
#         parsed_2 = re.sub('[,]', '', parsed_1)
#         finished = float(parsed_2) 
#     except:
#         url = f"https://www.marketwatch.com/investing/stock/{stock}"
#         browser.visit(url)
#         html = browser.html
#         soup = bs(html, 'html.parser')
#         pe = soup.find("div", class_="element element--list").text
#         parsed_1 = re.split(r'\b\n\b|:|- ',pe)[8]
#         parsed_2 = re.sub('[\n]', ' ', parsed_1)
#         parsed_3 = re.split(r'\bEPS\b|:|- ',parsed_2)[0]
#         finished = float(parsed_3)
#     stock_PE.append(finished)

# # Scrape EPS
# for stock in stock_list:
#     url = f"https://www.nasdaq.com/symbol/{stock}/earnings-forecast"
#     browser.visit(url)
#     html = browser.html
#     soup = bs(html, 'html.parser')
#     symbol  = soup.find("div", class_="genTable").find_all('tr')
#     data_str = str(symbol)
#     b_soup = bs(data_str)
#     data_text = b_soup.get_text()
#     try:
#         parsed_1 = re.split(r'\b\n\b|:|- ',data_text)[8]
#         finished = float(parsed_1)
#     except:
#         parsed_1 = re.split(r'\b\n\b|:|- ',data_text)[7]
#         parsed_2 = ab = re.sub('[\n]', ' ', parsed_1)
#         parsed_3 = re.sub('[ ]', ',', parsed_2)[-5:]
#         finished = float(parsed_3)
#     stock_eps.append(finished)

# # ZIP to stock symbol
# d_zip = list(zip(stock_list, stock_price, stock_PE, stock_dump, t, w, u))
# d_zip

In [11]:
# Put zipped data into dataframe
# df2 = pd.DataFrame(d_zip)
# df2 = df2.to_csv('data2.csv')

In [13]:
# Push dataframe to MySQL
# df.to_sql(name='finally', con=engine, if_exists='append', index=False)

In [66]:
# # Multiply EPS by PE Ratio

# # type(sub_ind)

# Find average PE Ratio grouped by Sub Industry
# sub_ind = sub_ind.groupby("sub_industry").mean()
# sub_ind_mean = sub_ind["pe_ratio"]
# sub_ind_mean_df = pd.DataFrame(sub_ind_mean)

# Merge Results
# result = pd.merge(sub_ind2, sub_ind_df, on=['sub_industry'])
# result = result.reset_index()

# Find current price by multiplying EST EPS by AVG PE Ratio
# current_price = result["est_eps"]*result["pe_ratio_y"]
# current_price = pd.DataFrame(current_price)
# result2 = current_price.reset_index()

# Merge Results
# result2 = pd.merge(result, result2, on=['index'])
# merged = result2.rename(columns={0: 'target_price'})

# Compute Percent change in Current Price and Target Price
# percent_change = (merged["target_price"]-merged['current_price'])/merged['current_price']*100
# percent_change = pd.DataFrame(percent_change)
# percent_change = percent_change.rename(columns={0: 'percent_change'})